import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'first react app',
  description: 'Generated by create-next-app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='overflow-hidden'>
      <body className={inter.className}><main>{children}</main></body>
    </html>
  )
}
